[content]
"Fundamentos da Programação" = { include = "./1ano1/FP/map.toml" }
"Modelação e análise de sistemas" = { include = "./1ano1/MAS/map.toml" }
"Álgebra Linear e Geometria Analítica" = { include = "./1ano1/Alga.toml" }
"Cálculo I" = { include = "./1ano1/CalcI.toml" }
"Modelação de Sistemas Físicos" = { include = "./1ano2/MSF/map.toml" }
