[children]
"Folhas de exercícios" = "https://uapt33090-my.sharepoint.com/:f:/g/personal/jcapucho_ua_pt/Ek8ApOEPLJNBsAwPjEHfqYsB-KBmMg0z-UCoeG2y8nlZOQ?e=4wCei0"
"Slides teóricos" = "https://uapt33090-my.sharepoint.com/:f:/g/personal/jcapucho_ua_pt/EtsY0LR81D1JuG5Dbq5kjbcB-t3ky9d6WomIZ-ICWN_M6w?e=YTzI6B"
Testes = "https://uapt33090-my.sharepoint.com/:f:/g/personal/jcapucho_ua_pt/EuqypuPh3BlNjYpRQRhUW4cBJXkA4KlE_AbIRY_P2qd0YA?e=ENqawy"

