[children."Aula 00".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/EUZZdlKtMBZLtJc9CbWULyYBmw3Sf3GiU1aGB0Wk6_zRyg?e=VxSzin"
"Resolução" = "aula01/guiao.norg"
