[children."Aula 00".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/Ef3QHqRi00BAkrBolrf2QkwBzFh8cg9wvmcdC8q7Xgh6kw?e=zhBZvu"
"Resolução" = "aula00/aula00.norg"

[children."Aula 01".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/EYoQDD-ZSO1MopgWyyhvELABgW9yPgdiZi-SSAYV0vmzFg?e=anZ8jt"
"Resolução" = "aula01/aula01.norg"

[children."Aula 02".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/ERwvWVd6HyJHj4O3LHN5J-8B4rBua91fPnL5-vBayxu17g?e=iedhcE"
"Resolução" = "aula02/aula02.norg"

[children."Aula 03".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/EcBJWOCmf6NGkYdtNfQ4aIIBLHmfAGrh1wn2C0sxzBgJFQ?e=b4m1yo"
"Resolução" = "aula03/aula03.norg"

[children."Aula 04".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/EZeg6drhFhJEqp5YoZmltksB6P12MWcBKqA22DD-z9MsCw?e=2S8O3m"
"Resolução" = "aula04/aula04.norg"

[children."Aula 05".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/Ec-pa5KcsrxCpW86j9eguDAB8Z9dulrwTWG4K-3umf-7nA?e=VjWewc"
"Resolução" = "aula05/aula05.norg"

[children."Aula 06".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/EWB5a0LS8GlCowfAZdz3NZMBBxkKeeBRGCdOBQqVu2dKOQ?e=JIDDvx"
"Resolução" = "aula06/aula06.norg"

[children."Aula 07".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/Eds6QOu8BM5IvJ0ofRCAZ9wBy2vFMPYHf2T2ScLuHLGfng?e=xjmjFD"
"Resolução" = "aula07/aula07.norg"

[children."Aula 08".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/EbfzvALWcYNMsY2gLvw4W9QBABa5I1pr4tHaqZN9YDM3-w?e=owfm9C"
"Resolução" = "aula08/aula08.norg"

[children."Aula 09".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/Ed7Iy0Vd2KpAjPvq3CybZSQBhBOTdU7fl6RyFW1RYSYONA?e=uMB3YZ"
"Resolução" = "aula09/aula09.norg"

[children."Aula 10".children]
Enunciado = "https://uapt33090-my.sharepoint.com/:b:/g/personal/jcapucho_ua_pt/EVjflqp7okNJsPq052dvO10BNt0bgqbxUU9j5FXYEkQWUg?e=A3FcRt"
"Resolução" = "aula10/aula10.norg"
