name: "Deploy"
on:
  push:
    branches: ["master"]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build application
        run: nix build --print-build-logs

      - name: Copy result
        run: cp --recursive --dereference --no-preserve=mode,ownership result public

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "public"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
